[
  {
    type: "ARTICLE",
    item: {
      articleId: 4,
      cafeId: 31719263,
      refArticleId: 4,
      replyArticleCount: 0,
      writerInfo: [Object],
      menuType: "B",
      menuId: 2,
      menuName: "공지",
      readLevel: 1,
      boardType: "L",
      restrictMenu: false,
      subject: "안녕하세요 서버 작동 테스트",
      writeDateTimestamp: 1777554147510,
      summary: "아아아",
      blindArticle: false,
      commentCount: 0,
      readCount: 1,
      hasCalender: false,
      hasFile: false,
      hasGpx: false,
      hasImage: false,
      hasLink: false,
      hasMap: false,
      hasMusic: false,
      hasMovie: false,
      hasPoll: false,
      likeCount: 0,
      newArticle: false,
      self: false,
      delParent: false,
      marketArticle: false,
      popular: false,
      openArticle: true,
      hasNewComment: false,
      enableComment: true,
      refArticle: false,
    },
  },
  {
    type: "ARTICLE",
    item: {
      articleId: 3,
      cafeId: 31719263,
      refArticleId: 3,
      replyArticleCount: 0,
      writerInfo: [Object],
      menuType: "B",
      menuId: 2,
      menuName: "공지",
      readLevel: 1,
      boardType: "L",
      restrictMenu: false,
      subject: "[테스트] 웹훅 테스트용2",
      writeDateTimestamp: 1777533648260,
      summary: "ㅇㅇㅇ",
      blindArticle: false,
      commentCount: 0,
      readCount: 2,
      hasCalender: false,
      hasFile: false,
      hasGpx: false,
      hasImage: false,
      hasLink: false,
      hasMap: false,
      hasMusic: false,
      hasMovie: false,
      hasPoll: false,
      likeCount: 0,
      newArticle: false,
      self: false,
      delParent: false,
      marketArticle: false,
      popular: false,
      openArticle: true,
      hasNewComment: false,
      enableComment: true,
      refArticle: false,
    },
  },
  {
    type: "ARTICLE",
    item: {
      articleId: 2,
      cafeId: 31719263,
      refArticleId: 2,
      replyArticleCount: 0,
      writerInfo: [Object],
      menuType: "B",
      menuId: 2,
      menuName: "공지",
      readLevel: 1,
      boardType: "L",
      restrictMenu: false,
      subject: "[테스트] 웹훅 테스트용1",
      writeDateTimestamp: 1777532414867,
      summary: "ㅇㅇ",
      blindArticle: false,
      commentCount: 0,
      readCount: 2,
      hasCalender: false,
      hasFile: false,
      hasGpx: false,
      hasImage: false,
      hasLink: false,
      hasMap: false,
      hasMusic: false,
      hasMovie: false,
      hasPoll: false,
      likeCount: 0,
      newArticle: false,
      self: false,
      delParent: false,
      marketArticle: false,
      popular: false,
      openArticle: true,
      hasNewComment: false,
      enableComment: true,
      refArticle: false,
    },
  },
  {
    type: "ARTICLE",
    item: {
      articleId: 1,
      cafeId: 31719263,
      refArticleId: 1,
      replyArticleCount: 0,
      writerInfo: [Object],
      menuType: "B",
      menuId: 1,
      menuName: "자유게시판",
      readLevel: 1,
      boardType: "L",
      restrictMenu: false,
      subject: "웹훅테스트용 카페를 시작합니다.",
      writeDateTimestamp: 1777532324673,
      summary: "",
      blindArticle: false,
      commentCount: 0,
      readCount: 0,
      hasCalender: false,
      hasFile: false,
      hasGpx: false,
      hasImage: false,
      hasLink: false,
      hasMap: false,
      hasMusic: false,
      hasMovie: false,
      hasPoll: false,
      likeCount: 0,
      newArticle: false,
      self: false,
      delParent: false,
      marketArticle: false,
      popular: false,
      openArticle: false,
      hasNewComment: false,
      enableComment: true,
      refArticle: false,
    },
  },
];
